<?xml version="1.0"?>
<!DOCTYPE COVStreetTrees [
<!ELEMENT COVStreetTrees ( StreetTree+ ) >
<!ELEMENT StreetTree ( CivicNumber, StdStreet, NeighbourhoodName, Cell, OnStreet, OnStreetBlock, StreetSideName, Assigned, HeightRangeID, Diameter, DatePlanted, PlantArea, Rootbarrier, Curb, CultivarName, GenusName, SpeciesName, CommonName ) >
<!ELEMENT CivicNumber ( #PCDATA ) >
<!ELEMENT StdStreet ( #PCDATA ) >
<!ELEMENT NeighbourhoodName ( #PCDATA ) >
<!ELEMENT Cell ( #PCDATA ) >
<!ELEMENT OnStreet ( #PCDATA ) >
<!ELEMENT OnStreetBlock ( #PCDATA ) >
<!ELEMENT StreetSideName ( #PCDATA ) >
<!ELEMENT Assigned ( #PCDATA ) >
<!ELEMENT HeightRangeID ( #PCDATA ) >
<!ELEMENT Diameter ( #PCDATA ) >
<!ELEMENT DatePlanted ( #PCDATA ) >
<!ELEMENT PlantArea ( #PCDATA ) >
<!ELEMENT RootBarrier ( #PCDATA ) >
<!ELEMENT Curb ( #PCDATA ) >
<!ELEMENT CultivarName ( #PCDATA ) >
<!ELEMENT GenusName ( #PCDATA ) >
<!ELEMENT SpeciesName ( #PCDATA ) >
<!ELEMENT CommonName ( #PCDATA ) >
<!ATTLIST COVStreetTrees ExtractDate CDATA #REQUIRED >
<!ATTLIST StreetTree TreeID ID #REQUIRED >
]>
<COVStreetTrees ExtractDate="2015-05-17">
   <StreetTree TreeID="2919">
    <CivicNumber>2707</CivicNumber>
    <StdStreet>W 35TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>11</Cell>
    <OnStreet>TRAFALGAR ST</OnStreet>
    <OnStreetBlock>5000</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>31</Diameter>
    <DatePlanted/>
    <PlantArea>B</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>AESCULUS</GenusName>
    <SpeciesName>HIPPOCASTANUM</SpeciesName>
    <CommonName>COMMON HORSECHESTNUT</CommonName>
  </StreetTree>
    <StreetTree TreeID="2920">
    <CivicNumber>2794</CivicNumber>
    <StdStreet>W 23RD AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>8</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3900</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090227</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2922">
    <CivicNumber>2794</CivicNumber>
    <StdStreet>W 23RD AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>10</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3900</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090227</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2923">
    <CivicNumber>2794</CivicNumber>
    <StdStreet>W 23RD AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>12</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3900</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1110">
    <CivicNumber>5410</CivicNumber>
    <StdStreet>BALSAM ST</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>16</Cell>
    <OnStreet>BALSAM ST</OnStreet>
    <OnStreetBlock>5400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>19</Diameter>
    <DatePlanted/>
    <PlantArea>L</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>FRAXINUS</GenusName>
    <SpeciesName>AMERICANA</SpeciesName>
    <CommonName>WHITE ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1114">
    <CivicNumber>5410</CivicNumber>
    <StdStreet>BALSAM ST</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>17</Cell>
    <OnStreet>BALSAM ST</OnStreet>
    <OnStreetBlock>5400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>17.5</Diameter>
    <DatePlanted/>
    <PlantArea>L</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>FRAXINUS</GenusName>
    <SpeciesName>AMERICANA</SpeciesName>
    <CommonName>WHITE ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="734">
    <CivicNumber>2250</CivicNumber>
    <StdStreet>W 33RD AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>W 33RD AV</OnStreet>
    <OnStreetBlock>2200</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>12</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MAGNOLIA</GenusName>
    <SpeciesName>KOBUS</SpeciesName>
    <CommonName>KOBUS MAGNOLIA </CommonName>
  </StreetTree>
    <StreetTree TreeID="762">
    <CivicNumber>5597</CivicNumber>
    <StdStreet>YEW ST</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>22</Cell>
    <OnStreet>W 40TH AV</OnStreet>
    <OnStreetBlock>2200</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>8</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>SHIROFUGEN</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>SERRULATA</SpeciesName>
    <CommonName>SHIROFUGEN CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="1492">
    <CivicNumber>5410</CivicNumber>
    <StdStreet>BALSAM ST</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>18</Cell>
    <OnStreet>BALSAM ST</OnStreet>
    <OnStreetBlock>5400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>20</Diameter>
    <DatePlanted/>
    <PlantArea>L</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>CAMPESTRE</SpeciesName>
    <CommonName>HEDGE MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2946">
    <CivicNumber>2799</CivicNumber>
    <StdStreet>W 23RD AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>20</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090210</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2951">
    <CivicNumber>2799</CivicNumber>
    <StdStreet>W 23RD AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>22</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090210</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2957">
    <CivicNumber>2799</CivicNumber>
    <StdStreet>W 23RD AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>24</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090210</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2960">
    <CivicNumber>2796</CivicNumber>
    <StdStreet>W 22ND AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>8</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090210</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2961">
    <CivicNumber>2796</CivicNumber>
    <StdStreet>W 22ND AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>10</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2962">
    <CivicNumber>2796</CivicNumber>
    <StdStreet>W 22ND AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>12</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2963">
    <CivicNumber>2796</CivicNumber>
    <StdStreet>W 21ST AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>8</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="2964">
    <CivicNumber>2796</CivicNumber>
    <StdStreet>W 21ST AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>10</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="2965">
    <CivicNumber>2796</CivicNumber>
    <StdStreet>W 21ST AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>12</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="2966">
    <CivicNumber>2797</CivicNumber>
    <StdStreet>W 21ST AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>20</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="2967">
    <CivicNumber>2797</CivicNumber>
    <StdStreet>W 21ST AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>22</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="2992">
    <CivicNumber>2793</CivicNumber>
    <StdStreet>W 20TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>20</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3500</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090211</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="966">
    <CivicNumber>2793</CivicNumber>
    <StdStreet>W 22ND AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>20</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090211</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="967">
    <CivicNumber>4038</CivicNumber>
    <StdStreet>MACDONALD ST</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>4000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="968">
    <CivicNumber>4038</CivicNumber>
    <StdStreet>MACDONALD ST</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>4000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="969">
    <CivicNumber>4038</CivicNumber>
    <StdStreet>MACDONALD ST</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>4000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090206</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>BOWHALL</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>RUBRUM</SpeciesName>
    <CommonName>BOWHALL RED MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1075">
    <CivicNumber>5505</CivicNumber>
    <StdStreet>TRAFALGAR ST</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>8</Cell>
    <OnStreet>W 39TH AV</OnStreet>
    <OnStreetBlock>2800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>9</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CORNUS</GenusName>
    <SpeciesName>CONTROVERSA</SpeciesName>
    <CommonName>GIANT DOGWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="1080">
    <CivicNumber>2162</CivicNumber>
    <StdStreet>W 33RD AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>W 33RD AV</OnStreet>
    <OnStreetBlock>2100</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>15.5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>PSEUDOPLATANUS</SpeciesName>
    <CommonName>SYCAMORE MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="4395">
    <CivicNumber>2798</CivicNumber>
    <StdStreet>W 20TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>8</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090211</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="4396">
    <CivicNumber>2798</CivicNumber>
    <StdStreet>W 20TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>10</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090211</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="4398">
    <CivicNumber>2793</CivicNumber>
    <StdStreet>W 19TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>20</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090211</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="4399">
    <CivicNumber>2793</CivicNumber>
    <StdStreet>W 19TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>22</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090211</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="4400">
    <CivicNumber>2793</CivicNumber>
    <StdStreet>W 19TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>24</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090211</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="4423">
    <CivicNumber>2788</CivicNumber>
    <StdStreet>W 18TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>10</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090414</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="4428">
    <CivicNumber>2788</CivicNumber>
    <StdStreet>W 18TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>12</Cell>
    <OnStreet>MACDONALD ST</OnStreet>
    <OnStreetBlock>3400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20090414</DatePlanted>
    <PlantArea>3</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>JAPONICA</SpeciesName>
    <CommonName>JAPANESE HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="6051">
    <CivicNumber>4325</CivicNumber>
    <StdStreet>PUGET DRIVE</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>PUGET DRIVE</OnStreet>
    <OnStreetBlock>4300</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20100215</DatePlanted>
    <PlantArea>4</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>IVORY SILK</CultivarName>
    <GenusName>SYRINGA</GenusName>
    <SpeciesName>RETICULATA</SpeciesName>
    <CommonName>TREE LILAC</CommonName>
  </StreetTree>
    <StreetTree TreeID="6075">
    <CivicNumber>4335</CivicNumber>
    <StdStreet>PUGET DRIVE</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>PUGET DRIVE</OnStreet>
    <OnStreetBlock>4300</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20100215</DatePlanted>
    <PlantArea>4</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>IVORY SILK</CultivarName>
    <GenusName>SYRINGA</GenusName>
    <SpeciesName>RETICULATA</SpeciesName>
    <CommonName>TREE LILAC</CommonName>
  </StreetTree>
    <StreetTree TreeID="3030">
    <CivicNumber>2408</CivicNumber>
    <StdStreet>W 20TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>20</Cell>
    <OnStreet>BALSAM ST</OnStreet>
    <OnStreetBlock>3600</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20120217</DatePlanted>
    <PlantArea>7</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CERCIDIPHYLLUM</GenusName>
    <SpeciesName>JAPONICUM</SpeciesName>
    <CommonName>KATSURA TREE</CommonName>
  </StreetTree>
    <StreetTree TreeID="7235">
    <CivicNumber>2996</CivicNumber>
    <StdStreet>W 21ST AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>W 21ST AV</OnStreet>
    <OnStreetBlock>2900</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>12</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>ABIES</GenusName>
    <SpeciesName>BALSAMEA</SpeciesName>
    <CommonName>BALSAM FIR </CommonName>
  </StreetTree>
    <StreetTree TreeID="7322">
    <CivicNumber>2996</CivicNumber>
    <StdStreet>W 21ST AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>8</Cell>
    <OnStreet>CARNARVON ST</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>6</HeightRangeID>
    <Diameter>35</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>PSEUDOTSUGA</GenusName>
    <SpeciesName>MENZIESII</SpeciesName>
    <CommonName>DOUGLAS FIR</CommonName>
  </StreetTree>
    <StreetTree TreeID="7323">
    <CivicNumber>2996</CivicNumber>
    <StdStreet>W 21ST AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>9</Cell>
    <OnStreet>CARNARVON ST</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>12</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AMERICANA</SpeciesName>
    <CommonName>AMERICAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="7461">
    <CivicNumber>2708</CivicNumber>
    <StdStreet>W 24TH AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>20</Cell>
    <OnStreet>TRAFALGAR ST</OnStreet>
    <OnStreetBlock>3900</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20111222</DatePlanted>
    <PlantArea>5</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>GLOBOSUM</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>PLATANOIDES</SpeciesName>
    <CommonName>GLOBEHEAD NORWAY MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="7462">
    <CivicNumber>2703</CivicNumber>
    <StdStreet>ALAMEIN AV</StdStreet>
    <NeighbourhoodName>ARBUTUS RIDGE</NeighbourhoodName>
    <Cell>10</Cell>
    <OnStreet>TRAFALGAR ST</OnStreet>
    <OnStreetBlock>3900</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>