<?xml version="1.0"?>
<!DOCTYPE COVStreetTrees [
<!ELEMENT COVStreetTrees ( StreetTree+ ) >
<!ELEMENT StreetTree ( CivicNumber, StdStreet, NeighbourhoodName, Cell, OnStreet, OnStreetBlock, StreetSideName, Assigned, HeightRangeID, Diameter, DatePlanted, PlantArea, Rootbarrier, Curb, CultivarName, GenusName, SpeciesName, CommonName ) >
<!ELEMENT CivicNumber ( #PCDATA ) >
<!ELEMENT StdStreet ( #PCDATA ) >
<!ELEMENT NeighbourhoodName ( #PCDATA ) >
<!ELEMENT Cell ( #PCDATA ) >
<!ELEMENT OnStreet ( #PCDATA ) >
<!ELEMENT OnStreetBlock ( #PCDATA ) >
<!ELEMENT StreetSideName ( #PCDATA ) >
<!ELEMENT Assigned ( #PCDATA ) >
<!ELEMENT HeightRangeID ( #PCDATA ) >
<!ELEMENT Diameter ( #PCDATA ) >
<!ELEMENT DatePlanted ( #PCDATA ) >
<!ELEMENT PlantArea ( #PCDATA ) >
<!ELEMENT RootBarrier ( #PCDATA ) >
<!ELEMENT Curb ( #PCDATA ) >
<!ELEMENT CultivarName ( #PCDATA ) >
<!ELEMENT GenusName ( #PCDATA ) >
<!ELEMENT SpeciesName ( #PCDATA ) >
<!ELEMENT CommonName ( #PCDATA ) >
<!ATTLIST COVStreetTrees ExtractDate CDATA #REQUIRED >
<!ATTLIST StreetTree TreeID ID #REQUIRED >
]>
<COVStreetTrees ExtractDate="2015-05-17">
   <StreetTree TreeID="554">
    <CivicNumber>1294</CivicNumber>
    <StdStreet>GRANVILLE ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>GRANVILLE ST</OnStreet>
    <OnStreetBlock>1200</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20091026</DatePlanted>
    <PlantArea>C</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>FAGUS</GenusName>
    <SpeciesName>SYLVATICA</SpeciesName>
    <CommonName>EUROPEAN BEECH</CommonName>
  </StreetTree>
    <StreetTree TreeID="2685">
    <CivicNumber>501</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>PACIFIC BOULEVARD</OnStreet>
    <OnStreetBlock>500</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>5.5</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>QUERCUS</GenusName>
    <SpeciesName>PALUSTRIS</SpeciesName>
    <CommonName>PIN OAK</CommonName>
  </StreetTree>
    <StreetTree TreeID="2701">
    <CivicNumber>501</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>PACIFIC BOULEVARD</OnStreet>
    <OnStreetBlock>500</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>11.5</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>FAGUS</GenusName>
    <SpeciesName>SYLVATICA</SpeciesName>
    <CommonName>EUROPEAN BEECH</CommonName>
  </StreetTree>
    <StreetTree TreeID="2706">
    <CivicNumber>1391</CivicNumber>
    <StdStreet>RICHARDS ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>RICHARDS ST</OnStreet>
    <OnStreetBlock>1300</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>6.5</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>PLATANOIDES</SpeciesName>
    <CommonName>NORWAY MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2718">
    <CivicNumber>501</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>8</Cell>
    <OnStreet>RICHARDS ST</OnStreet>
    <OnStreetBlock>1300</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>6</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>PLATANOIDES</SpeciesName>
    <CommonName>NORWAY MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2736">
    <CivicNumber>828</CivicNumber>
    <StdStreet>DRAKE ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>DRAKE ST</OnStreet>
    <OnStreetBlock>800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20111206</DatePlanted>
    <PlantArea>C</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>VANESSA</CultivarName>
    <GenusName>PARROTIA</GenusName>
    <SpeciesName>PERSICA</SpeciesName>
    <CommonName>VANESSA PERSIAN IRONWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="2644">
    <CivicNumber>501</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>PACIFIC BOULEVARD</OnStreet>
    <OnStreetBlock>500</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>QUERCUS</GenusName>
    <SpeciesName>RUBRA</SpeciesName>
    <CommonName>RED OAK</CommonName>
  </StreetTree>
    <StreetTree TreeID="2645">
    <CivicNumber>501</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>PACIFIC BOULEVARD</OnStreet>
    <OnStreetBlock>500</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>10</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>QUERCUS</GenusName>
    <SpeciesName>PALUSTRIS</SpeciesName>
    <CommonName>PIN OAK</CommonName>
  </StreetTree>
    <StreetTree TreeID="2648">
    <CivicNumber>501</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>PACIFIC BOULEVARD</OnStreet>
    <OnStreetBlock>500</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>QUERCUS</GenusName>
    <SpeciesName>RUBRA</SpeciesName>
    <CommonName>RED OAK</CommonName>
  </StreetTree>
    <StreetTree TreeID="2656">
    <CivicNumber>501</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>PACIFIC BOULEVARD</OnStreet>
    <OnStreetBlock>500</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>6.5</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>QUERCUS</GenusName>
    <SpeciesName>PALUSTRIS</SpeciesName>
    <CommonName>PIN OAK</CommonName>
  </StreetTree>
    <StreetTree TreeID="2659">
    <CivicNumber>501</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>5</Cell>
    <OnStreet>PACIFIC BOULEVARD</OnStreet>
    <OnStreetBlock>500</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>7.5</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>QUERCUS</GenusName>
    <SpeciesName>RUBRA</SpeciesName>
    <CommonName>RED OAK</CommonName>
  </StreetTree>
    <StreetTree TreeID="703">
    <CivicNumber>0</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1872">
    <CivicNumber>0</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>4.5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1874">
    <CivicNumber>0</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1875">
    <CivicNumber>0</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>5.5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="722">
    <CivicNumber>58</CivicNumber>
    <StdStreet>KEEFER PLACE</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>KEEFER PLACE</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20081202</DatePlanted>
    <PlantArea>C</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>FASTIGIATA</CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>BETULUS</SpeciesName>
    <CommonName>PYRAMIDAL EUROPEAN HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="727">
    <CivicNumber>80</CivicNumber>
    <StdStreet>KEEFER PLACE</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>KEEFER PLACE</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20081202</DatePlanted>
    <PlantArea>C</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>Y</Curb><CultivarName>FASTIGIATA</CultivarName>
    <GenusName>CARPINUS</GenusName>
    <SpeciesName>BETULUS</SpeciesName>
    <CommonName>PYRAMIDAL EUROPEAN HORNBEAM</CommonName>
  </StreetTree>
    <StreetTree TreeID="728">
    <CivicNumber>1177</CivicNumber>
    <StdStreet>W HASTINGS ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>W HASTINGS ST</OnStreet>
    <OnStreetBlock>1100</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>C</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>QUERCUS</GenusName>
    <SpeciesName>PALUSTRIS</SpeciesName>
    <CommonName>PIN OAK</CommonName>
  </StreetTree>
    <StreetTree TreeID="759">
    <CivicNumber>455</CivicNumber>
    <StdStreet>ABBOTT ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>ABBOTT ST</OnStreet>
    <OnStreetBlock>400</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>C</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>QUEEN ELIZABETH</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>CAMPESTRE</SpeciesName>
    <CommonName>QUEEN ELIZABETH MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1744">
    <CivicNumber>0</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>5</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>5.5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1768">
    <CivicNumber>0</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1769">
    <CivicNumber>0</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>5.5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1770">
    <CivicNumber>1</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>6.5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1771">
    <CivicNumber>1</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>5.5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1772">
    <CivicNumber>1</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1773">
    <CivicNumber>1</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>5</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>6</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="2741">
    <CivicNumber>1</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>5</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>5</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="6600">
    <CivicNumber>1002</CivicNumber>
    <StdStreet>SEYMOUR ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>SEYMOUR ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20121023</DatePlanted>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PARROTIA</GenusName>
    <SpeciesName>PERSICA</SpeciesName>
    <CommonName>PERSIAN IRONWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="6601">
    <CivicNumber>1002</CivicNumber>
    <StdStreet>SEYMOUR ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>SEYMOUR ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3.5</Diameter>
    <DatePlanted>20121023</DatePlanted>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PARROTIA</GenusName>
    <SpeciesName>PERSICA</SpeciesName>
    <CommonName>PERSIAN IRONWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="6602">
    <CivicNumber>1010</CivicNumber>
    <StdStreet>SEYMOUR ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>SEYMOUR ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20121023</DatePlanted>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PARROTIA</GenusName>
    <SpeciesName>PERSICA</SpeciesName>
    <CommonName>PERSIAN IRONWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="6606">
    <CivicNumber>1018</CivicNumber>
    <StdStreet>SEYMOUR ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>SEYMOUR ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>11.5</Diameter>
    <DatePlanted>20121023</DatePlanted>
    <PlantArea>C</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>TILIA</GenusName>
    <SpeciesName>EUCHLORA   X</SpeciesName>
    <CommonName>CRIMEAN LINDEN</CommonName>
  </StreetTree>
    <StreetTree TreeID="6611">
    <CivicNumber>1</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>6</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="4579">
    <CivicNumber>493</CivicNumber>
    <StdStreet>ROBSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>ROBSON ST</OnStreet>
    <OnStreetBlock>400</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>C</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>LIRIODENDRON</GenusName>
    <SpeciesName>TULIPIFERA</SpeciesName>
    <CommonName>TULIPTREE</CommonName>
  </StreetTree>
    <StreetTree TreeID="5587">
    <CivicNumber>1</CivicNumber>
    <StdStreet>NELSON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>NELSON ST</OnStreet>
    <OnStreetBlock>0</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>6</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>SORBUS</GenusName>
    <SpeciesName>AUCUPARIA</SpeciesName>
    <CommonName>EUROPEAN MOUNTAIN ASH</CommonName>
  </StreetTree>
    <StreetTree TreeID="4436">
    <CivicNumber>751</CivicNumber>
    <StdStreet>HAMILTON ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>HAMILTON ST</OnStreet>
    <OnStreetBlock>700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>Y</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>4</Diameter>
    <DatePlanted/>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>LIRIODENDRON</GenusName>
    <SpeciesName>TULIPIFERA</SpeciesName>
    <CommonName>TULIPTREE</CommonName>
  </StreetTree>
    <StreetTree TreeID="4466">
    <CivicNumber>1022</CivicNumber>
    <StdStreet>SEYMOUR ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>SEYMOUR ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>4</Diameter>
    <DatePlanted>20121026</DatePlanted>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PARROTIA</GenusName>
    <SpeciesName>PERSICA</SpeciesName>
    <CommonName>PERSIAN IRONWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="3435">
    <CivicNumber>110</CivicNumber>
    <StdStreet>DAVIE ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>26</Cell>
    <OnStreet>DAVIE ST</OnStreet>
    <OnStreetBlock>100</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CRATAEGUS</GenusName>
    <SpeciesName>LAVALLEI  X</SpeciesName>
    <CommonName>LAVALLEI HYBRID HAWTHORN</CommonName>
  </StreetTree>
    <StreetTree TreeID="3437">
    <CivicNumber>116</CivicNumber>
    <StdStreet>DAVIE ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>27</Cell>
    <OnStreet>DAVIE ST</OnStreet>
    <OnStreetBlock>100</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>3</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>CRATAEGUS</GenusName>
    <SpeciesName>LAVALLEI  X</SpeciesName>
    <CommonName>LAVALLEI HYBRID HAWTHORN</CommonName>
  </StreetTree>
    <StreetTree TreeID="4522">
    <CivicNumber>1022</CivicNumber>
    <StdStreet>SEYMOUR ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>SEYMOUR ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3.5</Diameter>
    <DatePlanted>20121026</DatePlanted>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PARROTIA</GenusName>
    <SpeciesName>PERSICA</SpeciesName>
    <CommonName>PERSIAN IRONWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="4523">
    <CivicNumber>1028</CivicNumber>
    <StdStreet>SEYMOUR ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>5</Cell>
    <OnStreet>SEYMOUR ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3.5</Diameter>
    <DatePlanted>20121023</DatePlanted>
    <PlantArea>G</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PARROTIA</GenusName>
    <SpeciesName>PERSICA</SpeciesName>
    <CommonName>PERSIAN IRONWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="4524">
    <CivicNumber>1032</CivicNumber>
    <StdStreet>SEYMOUR ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>SEYMOUR ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20121023</DatePlanted>
    <PlantArea>4</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PARROTIA</GenusName>
    <SpeciesName>PERSICA</SpeciesName>
    <CommonName>PERSIAN IRONWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="4068">
    <CivicNumber>500</CivicNumber>
    <StdStreet>PACIFIC BOULEVARD</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>26</Cell>
    <OnStreet>PACIFIC BOULEVARD</OnStreet>
    <OnStreetBlock>500</OnStreetBlock>
    <StreetSideName>MED</StreetSideName>
    <Assigned>Y</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20070601</DatePlanted>
    <PlantArea>6</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>EMERALD QUEEN</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>PLATANOIDES</SpeciesName>
    <CommonName>EMERALD QUEEN NORWAY MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="7642">
    <CivicNumber>1068</CivicNumber>
    <StdStreet>RICHARDS ST</StdStreet>
    <NeighbourhoodName>DOWNTOWN</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>RICHARDS ST</OnStreet>
    <OnStreetBlock>1000</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>