<?xml version="1.0"?>
<!DOCTYPE COVStreetTrees [
<!ELEMENT COVStreetTrees ( StreetTree+ ) >
<!ELEMENT StreetTree ( CivicNumber, StdStreet, NeighbourhoodName, Cell, OnStreet, OnStreetBlock, StreetSideName, Assigned, HeightRangeID, Diameter, DatePlanted, PlantArea, Rootbarrier, Curb, CultivarName, GenusName, SpeciesName, CommonName ) >
<!ELEMENT CivicNumber ( #PCDATA ) >
<!ELEMENT StdStreet ( #PCDATA ) >
<!ELEMENT NeighbourhoodName ( #PCDATA ) >
<!ELEMENT Cell ( #PCDATA ) >
<!ELEMENT OnStreet ( #PCDATA ) >
<!ELEMENT OnStreetBlock ( #PCDATA ) >
<!ELEMENT StreetSideName ( #PCDATA ) >
<!ELEMENT Assigned ( #PCDATA ) >
<!ELEMENT HeightRangeID ( #PCDATA ) >
<!ELEMENT Diameter ( #PCDATA ) >
<!ELEMENT DatePlanted ( #PCDATA ) >
<!ELEMENT PlantArea ( #PCDATA ) >
<!ELEMENT RootBarrier ( #PCDATA ) >
<!ELEMENT Curb ( #PCDATA ) >
<!ELEMENT CultivarName ( #PCDATA ) >
<!ELEMENT GenusName ( #PCDATA ) >
<!ELEMENT SpeciesName ( #PCDATA ) >
<!ELEMENT CommonName ( #PCDATA ) >
<!ATTLIST COVStreetTrees ExtractDate CDATA #REQUIRED >
<!ATTLIST StreetTree TreeID ID #REQUIRED >
]>
<COVStreetTrees ExtractDate="2015-06-07">
   <StreetTree TreeID="589">
    <CivicNumber>4694</CivicNumber>
    <StdStreet>W 8TH AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>12</Cell>
    <OnStreet>BLANCA ST</OnStreet>
    <OnStreetBlock>2400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>32</Diameter>
    <DatePlanted/>
    <PlantArea>B</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>ALNUS</GenusName>
    <SpeciesName>RUGOSA</SpeciesName>
    <CommonName>SPECKLED ALDER</CommonName>
  </StreetTree>
    <StreetTree TreeID="2180">
    <CivicNumber>4786</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>7</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>RHUS</GenusName>
    <SpeciesName>TYPHINA</SpeciesName>
    <CommonName>STAGHORN SUMAC</CommonName>
  </StreetTree>
    <StreetTree TreeID="1909">
    <CivicNumber>3707</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>24</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>BETULA</GenusName>
    <SpeciesName>NIGRA</SpeciesName>
    <CommonName>RIVER BIRCH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1910">
    <CivicNumber>3707</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>5</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>22</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>BETULA</GenusName>
    <SpeciesName>NIGRA</SpeciesName>
    <CommonName>RIVER BIRCH</CommonName>
  </StreetTree>
    <StreetTree TreeID="1915">
    <CivicNumber>3708</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>23</Cell>
    <OnStreet>ALMA ST</OnStreet>
    <OnStreetBlock>1800</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>16</Diameter>
    <DatePlanted/>
    <PlantArea>6</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>ATROPURPUREUM</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>CERASIFERA</SpeciesName>
    <CommonName>PISSARD PLUM</CommonName>
  </StreetTree>
    <StreetTree TreeID="1917">
    <CivicNumber>3732</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>14</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1920">
    <CivicNumber>3738</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>14</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1922">
    <CivicNumber>3755</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>10</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1925">
    <CivicNumber>3768</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>18</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1928">
    <CivicNumber>3791</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>12.25</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1943">
    <CivicNumber>3805</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>8</Cell>
    <OnStreet>HIGHBURY ST</OnStreet>
    <OnStreetBlock>1700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>24</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName>PLENA</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>AVIUM</SpeciesName>
    <CommonName>WILD CHERRY </CommonName>
  </StreetTree>
    <StreetTree TreeID="1946">
    <CivicNumber>3805</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>10</Cell>
    <OnStreet>HIGHBURY ST</OnStreet>
    <OnStreetBlock>1700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>20</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName>PLENA</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>AVIUM</SpeciesName>
    <CommonName>WILD CHERRY </CommonName>
  </StreetTree>
    <StreetTree TreeID="1947">
    <CivicNumber>3805</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>12</Cell>
    <OnStreet>HIGHBURY ST</OnStreet>
    <OnStreetBlock>1700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>5</HeightRangeID>
    <Diameter>22.5</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName>PLENA</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>AVIUM</SpeciesName>
    <CommonName>WILD CHERRY </CommonName>
  </StreetTree>
    <StreetTree TreeID="1950">
    <CivicNumber>3808</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>19</Cell>
    <OnStreet>HIGHBURY ST</OnStreet>
    <OnStreetBlock>1800</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>24</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>SARGENTII</SpeciesName>
    <CommonName>SARGENT FLOWERING CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="1952">
    <CivicNumber>3808</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>21</Cell>
    <OnStreet>HIGHBURY ST</OnStreet>
    <OnStreetBlock>1800</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>30</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>SARGENTII</SpeciesName>
    <CommonName>SARGENT FLOWERING CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="1957">
    <CivicNumber>3816</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>14</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1958">
    <CivicNumber>3817</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>14</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1962">
    <CivicNumber>3822</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>16</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1963">
    <CivicNumber>3831</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>4</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1965">
    <CivicNumber>3838</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>18</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1968">
    <CivicNumber>3847</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>14</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1969">
    <CivicNumber>3852</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>5</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>13</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1970">
    <CivicNumber>3853</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>18</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="1971">
    <CivicNumber>3853</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>19</Cell>
    <OnStreet>WALLACE ST</OnStreet>
    <OnStreetBlock>1700</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>15</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>TSUGA</GenusName>
    <SpeciesName>HETEROPHYLLA</SpeciesName>
    <CommonName>WESTERN HEMLOCK</CommonName>
  </StreetTree>
    <StreetTree TreeID="971">
    <CivicNumber>3861</CivicNumber>
    <StdStreet>W 1ST AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>W 1ST AV</OnStreet>
    <OnStreetBlock>3800</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>10</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>N</Curb><CultivarName> </CultivarName>
    <GenusName>CORNUS</GenusName>
    <SpeciesName>FLORIDA</SpeciesName>
    <CommonName>FLOWERING DOGWOOD</CommonName>
  </StreetTree>
    <StreetTree TreeID="892">
    <CivicNumber>4593</CivicNumber>
    <StdStreet>W 11TH AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>22</Cell>
    <OnStreet>TOLMIE ST</OnStreet>
    <OnStreetBlock>2600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20081216</DatePlanted>
    <PlantArea>8</PlantArea>
    <RootBarrier>Y</RootBarrier>
    <Curb>N</Curb><CultivarName>GLOBOSUM</CultivarName>
    <GenusName>ACER</GenusName>
    <SpeciesName>PLATANOIDES</SpeciesName>
    <CommonName>GLOBEHEAD NORWAY MAPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2103">
    <CivicNumber>4638</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>7</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>21</Diameter>
    <DatePlanted/>
    <PlantArea>6</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>SHIROFUGEN</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>SERRULATA</SpeciesName>
    <CommonName>SHIROFUGEN CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="2105">
    <CivicNumber>4648</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>19</Diameter>
    <DatePlanted/>
    <PlantArea>6</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>UKON</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>SERRULATA</SpeciesName>
    <CommonName>UKON JAPANESE CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="2106">
    <CivicNumber>4680</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>13</Diameter>
    <DatePlanted/>
    <PlantArea>6</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>UKON</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>SERRULATA</SpeciesName>
    <CommonName>UKON JAPANESE CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="2107">
    <CivicNumber>4686</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4600</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>10</Diameter>
    <DatePlanted/>
    <PlantArea>6</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>UKON</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>SERRULATA</SpeciesName>
    <CommonName>UKON JAPANESE CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="2109">
    <CivicNumber>4715</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>17.5</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>ATROPURPUREUM</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>CERASIFERA</SpeciesName>
    <CommonName>PISSARD PLUM</CommonName>
  </StreetTree>
    <StreetTree TreeID="2120">
    <CivicNumber>4727</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>5.25</Diameter>
    <DatePlanted>20020212</DatePlanted>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>AKEBONO</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>YEDOENSIS   X</SpeciesName>
    <CommonName>AKEBONO FLOWERING CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="2124">
    <CivicNumber>4735</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>3</HeightRangeID>
    <Diameter>14</Diameter>
    <DatePlanted/>
    <PlantArea>12</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>ATROPURPUREUM</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>CERASIFERA</SpeciesName>
    <CommonName>PISSARD PLUM</CommonName>
  </StreetTree>
    <StreetTree TreeID="2128">
    <CivicNumber>4741</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>4</HeightRangeID>
    <Diameter>18</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>SERRULATA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CHERRY </CommonName>
  </StreetTree>
    <StreetTree TreeID="2140">
    <CivicNumber>4755</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20020213</DatePlanted>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>AKEBONO</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>YEDOENSIS   X</SpeciesName>
    <CommonName>AKEBONO FLOWERING CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="2141">
    <CivicNumber>4755</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted>20000213</DatePlanted>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>AKEBONO</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>YEDOENSIS   X</SpeciesName>
    <CommonName>AKEBONO FLOWERING CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="2142">
    <CivicNumber>4755</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>10</Diameter>
    <DatePlanted>20020213</DatePlanted>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName>AKEBONO</CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>YEDOENSIS   X</SpeciesName>
    <CommonName>AKEBONO FLOWERING CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="2143">
    <CivicNumber>4763</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>2</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2145">
    <CivicNumber>4763</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>4</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2148">
    <CivicNumber>4763</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2150">
    <CivicNumber>4773</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>1</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="2153">
    <CivicNumber>4773</CivicNumber>
    <StdStreet>W 2ND AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>3</Cell>
    <OnStreet>W 2ND AV</OnStreet>
    <OnStreetBlock>4700</OnStreetBlock>
    <StreetSideName>ODD</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>1</HeightRangeID>
    <Diameter>3</Diameter>
    <DatePlanted/>
    <PlantArea>10</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>MALUS</GenusName>
    <SpeciesName>FLORIBUNDA</SpeciesName>
    <CommonName>JAPANESE FLOWERING CRABAPPLE</CommonName>
  </StreetTree>
    <StreetTree TreeID="979">
    <CivicNumber>4434</CivicNumber>
    <StdStreet>W 1ST AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>5</Cell>
    <OnStreet>W 1ST AV</OnStreet>
    <OnStreetBlock>4400</OnStreetBlock>
    <StreetSideName>EVEN</StreetSideName>
    <Assigned>N</Assigned>
    <HeightRangeID>2</HeightRangeID>
    <Diameter>6</Diameter>
    <DatePlanted/>
    <PlantArea>N</PlantArea>
    <RootBarrier>N</RootBarrier>
    <Curb>Y</Curb><CultivarName> </CultivarName>
    <GenusName>PRUNUS</GenusName>
    <SpeciesName>AVIUM</SpeciesName>
    <CommonName>MAZZARD CHERRY</CommonName>
  </StreetTree>
    <StreetTree TreeID="981">
    <CivicNumber>4434</CivicNumber>
    <StdStreet>W 1ST AV</StdStreet>
    <NeighbourhoodName>WEST POINT GREY</NeighbourhoodName>
    <Cell>6</Cell>
    <OnStreet>W 1ST AV</OnStreet>